---
- name: Add spotify apt repo key.
  apt_key:
    url: "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x13B00F1FD2C19886"
    id: "BBEBDCB318AD50EC6865090613B00F1FD2C19886"
    state: present

- name: Add spotify apt repo.
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
